version: '3'

services:

  zeebe: # https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#zeebe
    image: camunda/zeebe:8.7.3
    container_name: zeebe
    ports:
      - '26500:26500'
      - '9600:9600'
      - '8080:8080'
    environment: # https://docs.camunda.io/docs/8.2/self-managed/zeebe-deployment/configuration/environment-variables/
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1
      # allow running with low disk space
      - ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK=0.998
      - ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK=0.999
      - 'JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m -XX:UseSVE=0'
      - ZEEBE_BROKER_BACKPRESSURE_ALGORITHM=aimd
      - ZEEBE_BROKER_BACKPRESSURE_AIMD_REQUESTTIMEOUT=1000ms
    restart: always
    networks:
      - test-network
    depends_on:
      - elasticsearch

  elasticsearch: # https://hub.docker.com/_/elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-8.9.2}
    container_name: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      # allow running with low disk space
      - cluster.routing.allocation.disk.threshold_enabled=false
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:UseSVE=0'
      - 'CLI_JAVA_OPTS=-XX:UseSVE=0'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:9200/_cat/health | grep -q green']
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - test-network

networks:
  test-network: